# Generated by Django 2.2.6 on 2019-10-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategoria'),
        ),
    ]
