# Generated by Django 2.2.6 on 2019-10-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.CreateModel(
            name='Producto_Subcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto')),
                ('subctegoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subcategoria')),
            ],
        ),
    ]
