# Generated by Django 2.2.6 on 2019-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
